name: docker build
on: push

jobs:
    gd:
      runs-on: ubuntu-latest
      steps:
      - name: Free Disk Space (Ubuntu)
        uses: jerryliang122/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true   
      
      - name: Checkout
        uses: actions/checkout@v2
          
      #- name: clone chatglm2-6b-32K
      #  run: |
      #    git clone https://huggingface.co/THUDM/chatglm2-6b-32k
      #    cd chatglm2-6b-32k && rm -rf .git

      # 设置 QEMU, 后面 docker buildx 依赖此.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
          # 设置 Docker buildx, 方便构建 Multi platform 镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # 登录腾讯docker
      - name: Login to Tencent docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建镜像, 并打 tag
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: jerryliang/self-hosted-docker:latest
 
